mqtt:
  enabled: true
  host: mqtt-broker
  port: 1883
  topic_prefix: frigate
  client_id: frigate
  user: '{FRIGATE_MQTT_USER}'
  password: '{FRIGATE_MQTT_PASSWORD}'

logger:
  default: info

record:
  enabled: true
  retain:
    days: 7
    mode: all

cameras:
  rtsp-garage:
    ffmpeg:
      inputs:
        - path: rtsp://rtsp-server:8554/rtsp-garage
          roles:
            - detect
            - record
    detect:
      enabled: true
      max_disappeared: 30
    record:
      enabled: true
      retain:
        days: 1
    objects:
      track: [person, vehicle]
    snapshots:
      enabled: true
      retain:
        default: 1

version: 0.15-1
